### ISSUE TITLE
Fix impossible screen combination

### ISSUE THREAD

**Issue by fruitbatsalad** [toddcblank/kidicarus-dungeon-randomizer#39]
https://clips.twitch.tv/SuccessfulNaiveBeanBabyRage

**Comment by toddcblank** [comment]
I think this is actually a door position bug.  If we move the door then the jump is fine from the right side of the screen to the left.

**Comment by toddcblank** [comment]
I moved doors on all of the world 3 end of screen possibilities to hopefully avoid anything impossible.
